#!/bin/bash

echo "Running mDNSFlush daemon..."
date >> /tmp/flush.log
killall -9 mDNSResponder
echo "Attempted to kill mDNSResponder..."
killall -9 mDNSResponderHelper
echo "Attempted to kill mDNSResponder..."

echo "Done. Quitting."

exit
