#!/bin/bash

echo "Running mDNSrestart daemon..."
date >> /tmp/mDNSrestart.log
killall -9 mDNSResponder
echo "Attempted to kill mDNSResponder..."
killall -9 mDNSResponderHelper
echo "Attempted to kill mDNSResponderHelper..."

echo "Done. Quitting."

exit
