#!/bin/bash

echo "Thanks for installing mDNSrestart!"
echo "mDNSrestart was made possible by mDNSFlush created by nathanaccidentally"
echo "You may fork the GitHub page to implement this."

echo "Changing permissions of daemon..."
chmod 0775 /etc/mDNSrestart
echo "Changed mDNSrestart to world writable."
echo "Changing file to executeable..."
chmod +x /etc/mDNSrestart
echo "Changed to executeable."
echo "Chaging owner to root..."
chown root:wheel /etc/mDNSrestart
echo "Permissions are set..."

echo "Done! You should probably reboot to test this"
