#!/bin/bash

echo ""
echo ""
echo "Thanks for installing mDNSrestart! its made by Anish S"
echo ""
echo "You can learn more about me on:"
echo "https://anishs.me/"
echo ""
echo "mDNSrestart was made possible by mDNSFlush created by nathanaccidentally"
echo ""
echo ""
echo "Changing permissions of daemon..."
chmod 0775 /etc/mDNSrestart
echo ""
echo "Changed mDNSrestart to world writable."
echo "Changing file to executeable..."
chmod +x /etc/mDNSrestart
echo "Changed to executeable."
echo "Chaging owner to root..."
chown root:wheel /etc/mDNSrestart
echo ""
echo "Permissions are set..."
echo ""
echo "Done! You should reboot and rejailbreak to test this"
